### ISSUE TITLE
Error When building on android studio 1.3.2

### ISSUE THREAD

**Issue by gakwaya** [red5pro/red5pro-android-app#7]
Hello,
I am trying to play around with this example to see what I can achieve with it in terms of streaming but I get the error : 

Error:A problem was found with the configuration of task ':Red5Pro:zipalignDebug'.
> File 'E:\AKAZI\red5Android\red5pro-android-app-master\Red5Pro\build\outputs\apk\Red5Pro-debug-unaligned.apk' specified for property 'inputFile' does not exist.

I am following the guide here : 
https://github.com/red5pro/red5pro-android-app/blob/master/SETUP-ANDROID-STUDIO.md

Is there a way around this?
[Sorry if this is a basic question as I am still new to the android world]
Thanks.

**Comment by beetlejesss** [comment]
Hi Daniel!
I saw similar errors when I tried to build this, and found that by default Android Studio was using my "local gradle version" instead of the project default.  In Android Studio, go to: Preferences, "Build, Execution, Deployment", Build Tools, Gradle - and make sure that the project is using the default gradle wrapper, not the "local gradle distribution". 
If you have any other errors or questions, please email us at red5pro@infrared5.com.
